CREATE TABLE genre (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL UNIQUE,
                       description VARCHAR(255)
);

CREATE TABLE member (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email VARCHAR(255) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        role VARCHAR(255) NOT NULL CHECK (role IN ('READER', 'WRITER', 'ADMIN')),
                        username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE book (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      description VARCHAR(255) NOT NULL,
                      characters BIGINT NOT NULL,
                      price INTEGER,
                      genre_id BIGINT NOT NULL,
                      author_id BIGINT NOT NULL,
                      FOREIGN KEY (genre_id) REFERENCES genre(id),
                      FOREIGN KEY (author_id) REFERENCES member(id)
);

CREATE TABLE library (
                         reader_id BIGINT NOT NULL,
                         book_id BIGINT NOT NULL,
                         PRIMARY KEY (reader_id, book_id),
                         FOREIGN KEY (reader_id) REFERENCES member(id),
                         FOREIGN KEY (book_id) REFERENCES book(id)
);